from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OFFICIAL = ROOT / "third_party" / "official_methods"
DATA_ROOT = ROOT / "data" / "official_mmseg"
ARTIFACT_ROOT = ROOT / "runs" / "artifacts" / "official_predictions"

VOCAB_FILES = {
    "voc20": ROOT / "configs" / "vocab" / "voc20.txt",
    "context59": ROOT / "configs" / "vocab" / "context_59.txt",
    "ade20k": ROOT / "configs" / "vocab" / "ade20k_150.txt",
    "coco_stuff164k": ROOT / "configs" / "vocab" / "coco_stuff_171.txt",
}

# For official-method reproduction, prefer the class-name files shipped by each
# official repo whenever they exist. The generated cls_tfovos_* files are kept as
# a record of the benchmark's canonical vocabulary, but they should not drive the
# official rows unless an official file is unavailable.
OFFICIAL_CLASS_FILES = {
    "context59": "cls_context59.txt",
    "ade20k": "cls_ade20k.txt",
    "coco_stuff164k": "cls_coco_stuff.txt",
}


def _rel(target: Path, link_parent: Path) -> str:
    return Path(target).resolve().relative_to(link_parent.resolve()) if False else str(target.resolve())


def _symlink(target: Path, link: Path) -> None:
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink():
        if link.resolve() == target.resolve():
            return
        link.unlink()
    elif link.exists():
        return
    link.symlink_to(_rel(target, link.parent))


def _write_ids(manifest: Path, out: Path) -> None:
    import json

    out.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    with manifest.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line)["image_id"])
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")


def _read_vocab(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _write_tfovos_class_files(cfg_dir: Path) -> None:
    for dataset, vocab_path in VOCAB_FILES.items():
        out = cfg_dir / f"cls_tfovos_{dataset}.txt"
        out.write_text("\n".join(_read_vocab(vocab_path)) + "\n", encoding="utf-8")


def _prepare_coco_label_train_ids(source_dir: Path, out_dir: Path) -> None:
    if out_dir.is_symlink():
        out_dir.unlink()
    out_dir.mkdir(parents=True, exist_ok=True)
    for source in source_dir.glob("*.png"):
        link_name = source.name if source.name.endswith("_labelTrainIds.png") else f"{source.stem}_labelTrainIds.png"
        link = out_dir / link_name
        if link.exists() or link.is_symlink():
            link.unlink()
        _symlink(source, link)


def prepare_data_tree() -> dict[str, Path]:
    voc20 = DATA_ROOT / "voc20"
    _symlink(ROOT / "data/raw/VOCdevkit/VOC2012/JPEGImages", voc20 / "JPEGImages")
    # Use original 1-indexed annotations (1-20=classes, 0=bg, 255=void) so mmseg's
    # reduce_zero_label works correctly. Our voc20_labels are 0-indexed and wrong here.
    _symlink(ROOT / "data/raw/VOCdevkit/VOC2012/SegmentationClass", voc20 / "SegmentationClass")
    _write_ids(ROOT / "data/manifests/voc20_val.jsonl", voc20 / "ImageSets/Segmentation/val.txt")

    context59 = DATA_ROOT / "context59"
    _symlink(ROOT / "data/raw/VOCdevkit/VOC2010/JPEGImages", context59 / "JPEGImages")
    # Use 1-indexed label maps (1-59=classes, 0=void) so mmseg's reduce_zero_label works.
    # Generated by scripts/prepare_manifests.py context59 → context59_labels_mmseg.
    _symlink(ROOT / "data/raw/context59_labels_mmseg", context59 / "SegmentationClassContext")
    _write_ids(ROOT / "data/manifests/context59_val.jsonl", context59 / "ImageSets/SegmentationContext/val.txt")

    coco = DATA_ROOT / "coco_stuff171"
    _symlink(ROOT / "data/raw/coco_stuff171/val2017", coco / "images/val2017")
    # MMSeg's COCOStuffDataset and these official repos use the conventional
    # COCO-Stuff labelTrainIds files, where 0 is unlabeled and dataset classes
    # occupy 1..171. The model outputs follow that convention, so feeding the
    # benchmark's 0-indexed standard masks here shifts every class by one.
    _prepare_coco_label_train_ids(
        ROOT / "data/raw/coco_stuff171_labels_mmseg_official",
        coco / "annotations/val2017",
    )

    return {
        "voc20": voc20,
        "context59": context59,
        "ade20k": ROOT / "data/raw/ADEChallengeData2016",
        "coco_stuff164k": coco,
    }


def _config_text(base_name: str, class_file: str, dataset_type: str, data_root: Path, img_path: str, seg_path: str,
                 ann_file: str | None, scale: tuple[int, int], reduce_zero_label: bool = False,
                 extra_model: dict | None = None, output_dir: Path | None = None) -> str:
    load_annotations = "dict(type='LoadAnnotations')"
    if reduce_zero_label:
        load_annotations = "dict(type='LoadAnnotations', reduce_zero_label=True)"
    ann = f",\n        ann_file={ann_file!r}" if ann_file else ""
    dataset_reduce = f",\n        reduce_zero_label={reduce_zero_label!r}" if reduce_zero_label else ""
    extra_model_lines = ""
    if extra_model:
        extra_model_lines = "".join(f"\n    {k}={v!r}," for k, v in extra_model.items())
    evaluator = ""
    if output_dir:
        evaluator = f"""

# Official mmseg IoUMetric output. This preserves prediction label maps for
# proposal exploratory metrics without changing model inference or mIoU logic.
test_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'], output_dir={str(output_dir)!r})
"""
    return f"""_base_ = './base_config.py'

model = dict(name_path='./configs/{class_file}',{extra_model_lines}
)

dataset_type = {dataset_type!r}
data_root = {str(data_root)!r}

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale={scale!r}, keep_ratio=True),
    {load_annotations},
    dict(type='PackSegInputs')
]

test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path={img_path!r}, seg_map_path={seg_path!r}){ann}{dataset_reduce},
        pipeline=test_pipeline))
{evaluator}
"""


_RESCLIP_EXTRA: dict[str, dict] = {
    "tfovos_voc20":          {"temp_thd": 0.10, "delete_same_entity": True, "attn_rcs_weights": [2.0, 0.6], "attn_sfr_weights": [2.1, 0.6]},
    "tfovos_context59":      {"temp_thd": 0.25, "delete_same_entity": True, "attn_rcs_weights": [2.0, 0.4], "attn_sfr_weights": [1.8, 0.7]},
    "tfovos_ade20k":         {"temp_thd": 0.25, "delete_same_entity": True, "attn_rcs_weights": [2.0, 0.3], "attn_sfr_weights": [2.1, 0.7]},
    "tfovos_coco_stuff164k": {"temp_thd": 0.11, "delete_same_entity": True, "attn_rcs_weights": [2.0, 0.4], "attn_sfr_weights": [1.8, 0.7]},
}


_CORRCLIP_EXTRA: dict[str, dict] = {
    "tfovos_voc20": {"instance_mask_path": "data/region_masks/voc"},
    "tfovos_context59": {"instance_mask_path": "data/region_masks/context"},
    "tfovos_ade20k": {"instance_mask_path": "data/region_masks/ade"},
    "tfovos_coco_stuff164k": {"instance_mask_path": "data/region_masks/coco"},
}


def _extra_model(repo_name: str, config_name: str) -> dict | None:
    if repo_name == "ResCLIP":
        return _RESCLIP_EXTRA[config_name]
    if repo_name == "CorrCLIP":
        return _CORRCLIP_EXTRA[config_name]
    if repo_name == "NACLIP" and config_name == "tfovos_voc20":
        # The official NACLIP VOC configs disable sliding-window inference.
        # Leaving the model default (slide_crop=224) depresses VOC20 by ~2.4 pp.
        return {"slide_crop": 0}
    return None


def write_repo_configs(repo: Path, roots: dict[str, Path]) -> None:
    cfg_dir = repo / "configs"
    if not cfg_dir.exists():
        return
    _write_tfovos_class_files(cfg_dir)
    coco_scale = (2048, 448) if repo.name == "SCLIP" else (2048, 336)
    configs = {
        "tfovos_voc20": _config_text(
            "voc20", "cls_tfovos_voc20.txt", "PascalVOC20Dataset", roots["voc20"],
            "JPEGImages", "SegmentationClass", "ImageSets/Segmentation/val.txt", (2048, 336),
            extra_model=_extra_model(repo.name, "tfovos_voc20"),
            output_dir=ARTIFACT_ROOT / repo.name.lower() / "voc20",
        ),
        "tfovos_context59": _config_text(
            "context59", OFFICIAL_CLASS_FILES["context59"], "PascalContext59Dataset", roots["context59"],
            "JPEGImages", "SegmentationClassContext", "ImageSets/SegmentationContext/val.txt", (2048, 336), True,
            extra_model=_extra_model(repo.name, "tfovos_context59"),
            output_dir=ARTIFACT_ROOT / repo.name.lower() / "context59",
        ),
        "tfovos_ade20k": _config_text(
            "ade20k", OFFICIAL_CLASS_FILES["ade20k"], "ADE20KDataset", roots["ade20k"],
            "images/validation", "annotations/validation", None, (2048, 336), True,
            extra_model=_extra_model(repo.name, "tfovos_ade20k"),
            output_dir=ARTIFACT_ROOT / repo.name.lower() / "ade20k",
        ),
        "tfovos_coco_stuff164k": _config_text(
            "coco", OFFICIAL_CLASS_FILES["coco_stuff164k"], "COCOStuffDataset", roots["coco_stuff164k"],
            "images/val2017", "annotations/val2017", None, coco_scale, False,
            extra_model=_extra_model(repo.name, "tfovos_coco_stuff164k"),
            output_dir=ARTIFACT_ROOT / repo.name.lower() / "coco_stuff164k",
        ),
    }
    for name, text in configs.items():
        (cfg_dir / f"cfg_{name}.py").write_text(text, encoding="utf-8")


def main() -> None:
    roots = prepare_data_tree()
    for repo_name in ["SCLIP", "NACLIP", "ResCLIP", "ProxyCLIP", "CorrCLIP"]:
        write_repo_configs(OFFICIAL / repo_name, roots)
    print(f"Prepared official MMSeg configs under {OFFICIAL}")


if __name__ == "__main__":
    main()
